---
title: "Course Overview"
description: |
  This page contains the functions we've covered over term so far! More coming soon!
output:
  distill::distill_article:
    toc: true
    toc_float: true
    theme: dans-theme.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(xaringanExtra)
xaringanExtra::use_clipboard()
library(emo)
```

### Functions we've covered so far:

<details>
  <summary>For using packages & tutorials:</summary>

- `install.packages()`
- `library()`
- `remotes::install_github()`
- `learnr::run_tutorial()`

</details>

<details>
  <summary>For importing data:</summary>

- `readr::read_csv()`
- `haven::read_sav()`

</details>

<details>
  <summary>For inspecting data:</summary>

- `print()`
- `View()`
- `head()`
- `tail()`
- `str()`
- `summary()`
- `names()`
- `ncol()`
- `nrow()`

</details>

<details>
  <summary>For wrangling data:</summary>

- `dplyr::select()`
- `dplyr::filter()`
- `dplyr::mutate()`
- `dplyr::rename()`
- `na.omit()`

</details>


<details>
  <summary>For summarising data:</summary>

- `dplyr::summarise()`
- `dplyr::group_by()`

</details>


<details>
  <summary>For visualising data:</summary>

- `ggplot2::ggplot()`
- `aes()`
- `geom_point()`
- `geom_smooth()`
- `stat_summary()`
- `labs()`
- `coord_cartesian()`
- `scale_y_continuous()`
- `theme_bw()`
- `theme_minimal()`
- `theme_classic()`
- `GGally::ggscatmat()`

</details>


<details>
  <summary>For statistical tests:</summary>

- `GGally::ggscatmat()`
- `correlation::correlation()`
- `t.test()`
- `effectsize::cohens_d()`
- `lm()`
- `robust::lmRob()`
- `parameters::model_parameters()`
- `summary()`
- `broom::tidy()`
- `broom::glance()`


</details>



<br>

