---
title: "Week 07: Data Viz"
output:
  distill::distill_article:
    toc: true
    toc_float: true
    theme: dans-theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
xaringanExtra::use_clipboard()
library(emo)
```

### HappyHouR 

Slides [(*open in a new tab*)](https://fundrmentals-slides.netlify.app/week_07/index.html){target="_blank"}
<!--

<iframe id="inlineFrameExample"
    title="Inline Frame Example"
    height="360"
    src="">
</iframe>
-->

### Complete the tutorial for next week: 

:::ojtask

Work through the discovr_09 tutorial on comparing means by pasting the below code into the **Console** in RStudio & pressing **Enter**.

```{r, eval = F, echo = T}

learnr::run_tutorial("discovr_09", package = "discovr")

```



:::

<br>

<div class="button-box col-lg-12">

<a href="https://fundrmentals.netlify.app/week_06.html">
<button class="button3">Previous week</button>
</a>
<a href="https://fundrmentals.netlify.app/week_08.html">
<button class="button4">Next week</button>
</a>

</div>

<br>
